name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - scikit-learn
  - psutil
  - toolz
  - matplotlib
  - altair
  - vega
  - vega_datasets
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - rpy2
